-- :break function - puts a breakpoint on that method
-- :continue - continus execution after breakpoint
-- :list - shows where we are in the execution
-- :show breaks - show all breakpoints in program
-- :show bindings - show all variables with their values
-- :abandon - ends debugging mode 